version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: database
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: dockertestdb
      MYSQL_USER: ddavid
      MYSQL_PASSWORD: davidpw
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 9906:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    restart: always
    environment:
      PMA_HOST: database
    depends_on:
      - database